# Generated by Django 3.0.6 on 2020-05-31 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ts_last_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
