# Generated by Django 3.0.6 on 2020-05-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_auto_20200531_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ts_last_created',
            new_name='ts_last_changed',
        ),
    ]
