# Generated by Django 3.0.6 on 2020-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('group', models.IntegerField(choices=[(1, 'garden'), (2, 'farm'), (3, 'animal'), (4, 'pets')])),
            ],
        ),
    ]
